### ISSUE TITLE
some advice

### ISSUE THREAD

**Issue by huohua0** [KiraLT/torrent-stream-server#140]
# how to deplay it to okteto?
## how to add my search to it?

**Comment by huohua0** [comment]
also,how to clear the history 
how to set a password

**Comment by huohua0** [comment]
# how about to support ed2k

**Comment by KiraLT** [comment]
If you wish to protect your app with a password, you can add `security.apiKey` parameter to the [config](https://kiralt.github.io/torrent-stream-server/docs/configuration). And you will require to enter the key if you wish to log in your UI or use API. 

Regarding deployment instructions, I am planning to expend documentation and include deployment tutorials to different systems. Heroku is not the best way to deploy this system, so I am planning to simplify deployment on Kubernetes or bare-metal server.

**Comment by KiraLT** [comment]
Added deployment to Okteto with one-click:

[![Develop on Okteto](https://okteto.com/develop-okteto.svg)](https://cloud.okteto.com/deploy?repository=https://github.com/KiraLT/torrent-stream-server&branch=master)

> _Okteto forbids P2P services, so your account can be suspended ([learn more](https://okteto.com/legal/)). So I suggest creating a new account with the intention that it may be suspended_
