### ISSUE TITLE
Limit download/upload speed

### ISSUE THREAD

**Issue by KiraLT** [KiraLT/torrent-stream-server#15]
Depending on the torrent you use, if it has a lot of seeders, download speed can consume all resources (in my cases download speed reaches `20 - 30 MB/s`).

The idea is to limit download/uploads speed. The limit can be global (for all active torrents) or for each individual torrent/file. The second option would be better, because for streaming `1MB/s` it's enough.

**Related:**

* [Limit download/upload speeds (throttling) ](https://github.com/webtorrent/webtorrent/issues/163).
* [Add speed limit (pull request)](https://github.com/webtorrent/webtorrent/pull/1969)

**Comment by KiraLT** [comment]
There are some movements regarding this issue on webtorrent/webtorrent#2062. Let's home It won't stop like all the previous 6 pull requests:
* webtorrent/webtorrent#1516
* webtorrent/webtorrent#1762
* webtorrent/webtorrent#1852
* webtorrent/webtorrent#1969
* webtorrent/webtorrent#2000
* webtorrent/webtorrent#2023

**Comment by omgbox** [comment]
> There are some movements regarding this issue on [webtorrent/webtorrent#2062](https://github.com/webtorrent/webtorrent/pull/2062). Let's home It won't stop like all the previous 6 pull requests:
> 
> * [webtorrent/webtorrent#1516](https://github.com/webtorrent/webtorrent/pull/1516)
> * [webtorrent/webtorrent#1762](https://github.com/webtorrent/webtorrent/pull/1762)
> * [webtorrent/webtorrent#1852](https://github.com/webtorrent/webtorrent/pull/1852)
> * [webtorrent/webtorrent#1969](https://github.com/webtorrent/webtorrent/pull/1969)
> * [webtorrent/webtorrent#2000](https://github.com/webtorrent/webtorrent/pull/2000)
> * [webtorrent/webtorrent#2023](https://github.com/webtorrent/webtorrent/pull/2023)

looks like its awaiting to be merged to branch but last commit webtorrent#2023 no approval or blocked , might be few weeks or at least few months to see it all green.

**Comment by KiraLT** [comment]
Finally, they released this feature, I will include this feature soon!

**Comment by omgbox** [comment]
> Finally, they released this feature, I will include this feature soon!

I wonder if it is per torrent or global preset which effects the entire engine.

**Comment by KiraLT** [comment]
Added speed limitations. Limitations are global, so when multiple torrents are downloading they will share network bandwidth.

There are two types:
* Download speed, default is 5MB/s. In most cases is more than enough, faster speed could crash NodeJS.
* Upload speed, default is 0. In many cases, you can't seed torrents (for legal reasons or when using services like Heroku).

These parameters can be changed by providing a config file or by ENV variables - [docs](https://kiralt.github.io/torrent-stream-server/docs/configuration)

**Comment by pataquets** [comment]
@KiraLT I've checked the docs and had a doubt. Does 0 for upload speed means 'do not upload' or 'unlimited upload'?

**Comment by KiraLT** [comment]
According to the [docs](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md):

> For downloadLimit and uploadLimit the possible values can be:
> 
> * `> 0`. The client will set the throttle at that speed
> * `0`. The client will block any data from being downloaded or uploaded
> * `-1`. The client will is disable the throttling and use the whole bandwidth available
