### ISSUE TITLE
{"error":"Unknown query parameter 'dn'"}

### ISSUE THREAD

**Issue by omgbox** [KiraLT/torrent-stream-server#170]
very recently forked updated repo and deployed to herokuapp, is the api the same ?

in this version with Chromecast this provides the error  `{"error":"Unknown query parameter 'dn'"}`
https://demo.herokuapp.com/stream?torrent=

in old repo without chromecast support, api worked 
https://demo.herokuapp.com/stream?torrent=

I'm going to delete the herokuapp again and fork your repo fresh again . i might have done something wrong.

**Comment by omgbox** [comment]
just installed everything , seems to have some problems with white spaces or characters being replaced 

this works in terminal 
`http://127.0.0.1:3000/stream/magnet%3A%3Fxt%3Durn%3Abtih%3AD171AFDF2AA`

while this does not work in terminal
`http://127.0.0.1:3000/stream/magnet:?xt=urn:btih:D171A`

you notice the start of magnet link having some of its characters replaced.

**Comment by KiraLT** [comment]
I am using a new API validation library, which is quite strict. In theory, this error is correct because you have an invalid URL format. But the is no point validating it on streaming API.

**Comment by omgbox** [comment]
> I am using a new API validation library, which is quite strict. In theory, this error is correct because you have an invalid URL format. But the is no point validating it on streaming API.

is there a way to set it to off for validation, right now I'm not able to use it for streaming through terminal I am still with the old repo.

**Comment by KiraLT** [comment]
You can use the previous API:
http://127.0.0.1:3000/stream?torrent=magnet:?xt=urn:btih:D171A

**Comment by omgbox** [comment]
> You can use the previous API:
> http://127.0.0.1:3000/stream?torrent=magnet:?xt=urn:btih:D171A

thanks I am currently using old API
