### ISSUE TITLE
What does "Torrents Space" mean?

### ISSUE THREAD

**Issue by AyaanZaveri** [KiraLT/torrent-stream-server#172]
![Screen Shot 2021-06-15 at 2 15 22 PM](https://user-images.githubusercontent.com/63752541/122103029-20b67c80-cde4-11eb-8606-31f5d2721f44.png)

I've been using **Okteto**, and it's working great, but what happens when the **Torrents Space** reaches the max amount?
Also, why does it show **79.68 / 96.75** for disk space if I've not downloaded something?

**Comment by KiraLT** [comment]
Disk space shows the total space your server has. There will always be used space on server disk space because at least the operating system and other things are installed in the server.

Torrents space shows disk space only for a specific directory - where are torrents stored. If you reach 100% of the torrent disk space, your app will probably crash. However, it shouldn't happen - all inactive torrents are automatically deleted and the less space you have, the more aggressive this algorithm is.

**Comment by AyaanZaveri** [comment]
Thanks! I just realized that I can get suspended from Okteto, so is there any other service that doesn't ban, like CircleCI?

**Comment by KiraLT** [comment]
No one likes Peer-to-peer services, so it's hard to say. If you are using the free tier, it's not a terrible thing to get suspened. Well, if you are looking for paid hosting, the safest solution would be to buy a cheap [VPS](https://kiralt.github.io/torrent-stream-server/docs/setup#vps) in a country where [torrenting](https://www.downloadprivacy.com/safest-countries-to-download-torrents) is safe.

**Comment by AyaanZaveri** [comment]
What about Netlify?

**Comment by KiraLT** [comment]
According to netlify [Terms of Use Agreement](https://www.netlify.com/legal/terms-of-use/), it may work.

It also has deploy button:

[![deploy](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=KiraLT/torrent-stream-server)

P. S. Not sure if it works, but I will work on it a bit later.

**Comment by AyaanZaveri** [comment]
It says "It looks like this is a Jekyll site, but you don't have a Gemfile. This will most likely lead to a broken build. Check out our Migrating your Jekyll site to Netlify guide to fix this issue before deploying your site." I think you'll need to add a "gemfile" to the project.

**Comment by AyaanZaveri** [comment]
https://www.netlify.com/blog/2017/05/11/migrating-your-jekyll-site-to-netlify/
I think it says to add a file called 'Gemfile' then add this content:

```
source "https://rubygems.org"
gem 'github-pages'
```

**Comment by AyaanZaveri** [comment]
On this website there are a lot of good free services that torrent-stream-server can use.
https://free-for.dev/#/?id=paas

**Comment by KiraLT** [comment]
Netlify won't work because it mostly is CDN and backend functionality is very limited. I will check other free servises.

**Comment by AyaanZaveri** [comment]
I tried Railway and I immediately got banned after seconds!

**Comment by AyaanZaveri** [comment]
A long time ago I deployed https://github.com/Davenchy/live-torrent to Heroku, and it's still up. Why is that???https://tornow.herokuapp.com/

**Comment by AyaanZaveri** [comment]
Did you find anything?

**Comment by AyaanZaveri** [comment]
I got it to work on Render!

**Comment by AyaanZaveri** [comment]
But I'm on a 7-day trial, so I don't think it will work after that.

**Comment by AyaanZaveri** [comment]
Would Firebase work?

**Comment by KiraLT** [comment]
Created a separate issue for finding more deployment options: #179
