### ISSUE TITLE
methods and selectors api 

### ISSUE THREAD

**Issue by omgbox** [KiraLT/torrent-stream-server#18]
please check [here](https://live-torrent-server.herokuapp.com/docs/api/torrent.html#tables) to get some idea about methods to add to TSS.

it would be nice to have, Selectors
Selectors that can be a Parameters or an Endpoint

example

Parameter | Type | Description | Example
-- | -- | -- | --
fileIndex | number | get file with its index | /torrent/serve/08ada5a7a6183aae1e09d831df6748d566095a10?fileIndex=0
filePath | string | get file with its path | /torrent/serve/08ada5a7a6183aae1e09d831df6748d566095a10/filePath=subtitles.en.vtt
fileType | string | get file with its type | /torrent/serve/08ada5a7a6183aae1e09d831df6748d566095a10/fileType=video
fileType | string | get file with its mime type | /torrent/serve/08ada5a7a6183aae1e09d831df6748d566095a10/fileType=.mp4

or endpoint

Name | Description | Endpoint
-- | -- | --
file index | get file with its index | /torrent/serve/08ada5a7a6183aae1e09d831df6748d566095a10/0
file path | get file with its path | /torrent/serve/08ada5a7a6183aae1e09d831df6748d566095a10/subtitles/subtitle.en.vtt
file type | get file with its type | /torrent/serve/08ada5a7a6183aae1e09d831df6748d566095a10/:video
file type | get file with its mime type | /torrent/serve/08ada5a7a6183aae1e09d831df6748d566095a10/:.mp4

something like live torrent stream api.

**Comment by KiraLT** [comment]
I added selector support for API. You can find documentation [here](https://kiralt.github.io/torrent-stream-server/docs/swagger.html#/stream/getStream).

But I am not sure about `fileIndex` parameter. Why should you wish to select a file by index? Do torrent files even has some specific order? When I display files, I re-sort them by file names.

Also, by default (or when selector matches multiple files) API returns the biggest file, which I think makes sense.

**Comment by omgbox** [comment]
> I added selector support for API. You can find documentation [here](https://kiralt.github.io/torrent-stream-server/docs/swagger.html#/stream/getStream).
> 
> But I am not sure about `fileIndex` parameter. Why should you wish to select a file by index? Do torrent files even has some specific order? When I display files, I re-sort them by file names.
> 
> Also, by default (or when selector matches multiple files) API returns the biggest file, which I think makes sense.

> When I display files, I re-sort them by file names.

brilliantly fast work, you did it, **&fileType=video%2Fmp4&fileIndex=1** , now users can select which file in multifile torrent to play from cli

i noticed some issue maybe is this normal or it should be **&fileType=video/mp4&fileIndex=1**   is there some space issue in swagger, it seemed to replace / to **%2F** to output.  

another good torrent [indexer](https://torrent-paradise.ml/), search based on ipfs, even if they take out the domain, users can still access the database through any public ipfs gateway. thepiratebay is good but its not being updated anymore with new content.

**Comment by KiraLT** [comment]
> it seemed to replace / to %2F to output

That is the correct behavior. All parameters are encoding using [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent). Well, technically without encoding also works (at least in most cases). 

> another good torrent indexer, search based on ipfs, even if they take out the domain, users can still access the database through any public ipfs gateway

It looks interesting. The only issue is that you can't filter by category.

**Comment by omgbox** [comment]
> > it seemed to replace / to %2F to output
> 
> That is the correct behavior. All parameters are encoding using [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent). Well, technically without encoding also works (at least in most cases).
> 
> > another good torrent indexer, search based on ipfs, even if they take out the domain, users can still access the database through any public ipfs gateway
> 
> It looks interesting. The only issue is that you can't filter by category.

shame , the developer especially disabled that feature to make it simple to use. ehh
