### ISSUE TITLE
Heroku Build Failing

### ISSUE THREAD

**Issue by dgbkn** [KiraLT/torrent-stream-server#187]
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  >=12.x
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >=12.x...
       Downloading and installing node 16.4.1...
       Using default npm version: 7.18.1
       
-----> Installing dependencies
       Installing node modules
       
       > torrent-stream-server@1.8.1 postinstall
       > [ ! -d frontend/src ] || npm --prefix frontend install
       
       
       added 2052 packages, and audited 2053 packages in 1m
       
       141 packages are looking for funding
         run `npm fund` for details
       
       30 vulnerabilities (4 low, 12 moderate, 14 high)
       
       To address issues that do not require attention, run:
         npm audit fix
       
       To address all issues (including breaking changes), run:
         npm audit fix --force
       
       Run `npm audit` for details.
       
       added 1431 packages, and audited 1432 packages in 2m
       
       143 packages are looking for funding
         run `npm fund` for details
       
       4 vulnerabilities (2 moderate, 2 high)
       
       To address all issues, run:
         npm audit fix
       
       Run `npm audit` for details.
       
-----> Build
       Running build
       
       > torrent-stream-server@1.8.1 build
       > npm run build-backend && npm run build-frontend
       
       
       > torrent-stream-server@1.8.1 build-backend
       > tsc
       
       
       > torrent-stream-server@1.8.1 build-frontend
       > npm run --prefix frontend build
       
       
       > torrent-stream-server-frontend@1.8.1 build
       > REACT_APP_VERSION=$npm_package_version SKIP_PREFLIGHT_CHECK=true react-scripts build
       
       Creating an optimized production build...
       Failed to compile.
       
       /tmp/build_c1979e7a/frontend/src/components/browse.tsx
       TypeScript error in /tmp/build_c1979e7a/frontend/src/components/browse.tsx(19,20):
       Could not find a declaration file for module 'react-select'. '/tmp/build_c1979e7a/frontend/node_modules/react-select/dist/react-select.cjs.js' implicitly has an 'any' type.
         Try `npm i --save-dev @types/react-select` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-select';`  TS7016
       
           17 | import { sortBy } from 'common-stuff'
           18 | import { useGlobal } from 'reactn'
         > 19 | import Select from 'react-select'
              |                    ^
           20 | 
           21 | import { BrowseApi, ProviderTorrentModel } from '../helpers/client'
           22 | import { useSearchParam, useSearchParamsHandler } from '../helpers/hooks'
       
       
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by KiraLT** [comment]
Fixed the issue, one type were saved as devDependencies, but Heroku removes dev dependencies when building.
