### ISSUE TITLE
possible issue with forward slash / domains

### ISSUE THREAD

**Issue by omgbox** [KiraLT/torrent-stream-server#19]
my apologies KiraLT, i am to much on here :)  i am having this small issue with a forward slash being added.

i have my domain setup for easy access from terminal like this

https://example.com/5E6C856FB0BB176BB18AA9EC6B11E9DC3BD4ADBE --- > would redirect to https://example.herokuapp.com/stream?torrent= and append the hash

now the issue,  it correctly adds hash but also appends a forward slash 

example.herokuapp.com/stream?torrent=/5E6C856FB0BB176BB18AA9EC6B11E9DC3BD4ADBE

 {"error":"Cannot parse torrent: Invalid torrent identifier, link: /5E6C856FB0BB176BB18AA9EC6B11E9DC3BD4ADBE"}

could torrent stream server be used  like this /stream/torrent/hash

**Comment by KiraLT** [comment]
Could you tell me more about your redirection system? Do you use some kind of tool or you are running custom service?

Regarding moving torrent path make sence, I will check more about it. But path can require more strict escaping comparing to query parameters.

**Comment by omgbox** [comment]
it is normal redirect , it is set for visible redirect nothing special . 

to a web address carry out a visible redirection Permanent (301):, 
www.cdn.example.com | Permanent visible redirection | example.herokuapp.com/stream?torrent=
-- | -- | --

 somewhere in the code its probably appending the forward slash, this issue does not appear with live torrent server.

**Comment by KiraLT** [comment]
I moved `torrent` from query to path, which makes sense (because it's the required parameter). Old URL redirects to the new one.

You can find documentation on [swagger page](https://kiralt.github.io/torrent-stream-server/docs/swagger.html#/stream/getStream).

Now you can use the following:
https://example.herokuapp.com/stream/5E6C856FB0BB176BB18AA9EC6B11E9DC3BD4ADBE

@omgbox  does this helps or you still need to remove `/`?

**Comment by omgbox** [comment]
> I moved `torrent` from query to path, which makes sense (because it's the required parameter). Old URL redirects to the new one.
> 
> You can find documentation on [swagger page](https://kiralt.github.io/torrent-stream-server/docs/swagger.html#/stream/getStream).
> 
> Now you can use the following:
> https://example.herokuapp.com/stream/5E6C856FB0BB176BB18AA9EC6B11E9DC3BD4ADBE
> 
> @omgbox does this helps or you still need to remove `/`?

awesome, it is successfully passing the hash, streaming working perfectly from the terminal. thank you for your efforts and your wonderful project KiraLT.
