### ISSUE TITLE
What kind of engine is used?

### ISSUE THREAD

**Issue by VuzzyM** [KiraLT/torrent-stream-server#194]
Libtorrent?

do you support these protocols?

Protocol obfuscation
DHT
uTP
PEX
Magnet links
IP Blocklists
Some IPv6
HTTP and UDP tracker clients

BEPs:

3: Basic BitTorrent protocol
5: DHT
6: Fast Extension (have all/none only)
7: IPv6 Tracker Extension
9: ut_metadata
10: Extension protocol
11: PEX
12: Multitracker metadata extension
15: UDP Tracker Protocol
20: Peer ID convention ("-GTnnnn-")
23: Tracker Returns Compact Peer Lists
27: Private torrents
29: uTorrent transport protocol
41: UDP Tracker Protocol Extensions
42: DHT Security extension
43: Read-only DHT Nodes

BEPs:

14: Local Peers Discovery
19: WebSeeds

**Comment by omgbox** [comment]
I believe it is currently using github.com/webtorrent/webtorrent only UDP TCP  , but would be much nicer to use https://github.com/webtorrent/webtorrent-hybrid , as it also connects to WebRTC users. i am not sure if the webtorrent right now uses WebRTC.

**Comment by KiraLT** [comment]
We use [Webtorrent](https://github.com/webtorrent/webtorrent) for streaming support, you can find all information on their Github. Not all functionality is implemented, so some features can be missing. Could you tell more specifically what you are looking for or maybe you are missing some functionality?
