### ISSUE TITLE
Naming Issue

### ISSUE THREAD

**Issue by AyaanZaveri** [KiraLT/torrent-stream-server#195]
Whenever I download a file, it ends up being magnet... instead of the actual file name.

**Comment by omgbox** [comment]
i dont have any issues with naming, clicking download , saves file with correct filename

**Comment by KiraLT** [comment]
There is the possibility that some browsers or devices do not get the correct file name. Could you provide information - your device, browser and how did you download the file (API, using user interface).

**Comment by AyaanZaveri** [comment]
It happens whenever I download using wget.

**Comment by KiraLT** [comment]
`wget` does not respect `Content-Disposition` header which indicated filename, so you need to add `--content-disposition` option:

```bash
wget --content-disposition 'http://localhost:3000/stream/08ada5a7a6183aae1e09d831df6748d566095a10'
```

Source: [unix.stackexchange.com](https://unix.stackexchange.com/a/394467)

**Comment by AyaanZaveri** [comment]
Thanks!
