### ISSUE TITLE
file support

### ISSUE THREAD

**Issue by toonsevrin** [KiraLT/torrent-stream-server#2]
Hi Kira, have you considered supporting file selection?

**Comment by KiraLT** [comment]
Using API you can select which file you wish to stream (specify `file` GET parameter in the URL):

```ts
const file = torrent.engine.files.find(f => f.name === data.file) || torrent.engine.files[0]
````
[Source](https://github.com/KiraLT/torrent-stream-server/blob/0f61912bd9b7ff33cee1f3dd7e757d3df6aee180/src/api/stream.ts#L38)

---

Still, I will need to add this support to the demo page.

**Comment by toonsevrin** [comment]
Awesome, would be pretty neat to have this feature on the demo page indeed :+1:

**Comment by KiraLT** [comment]
I just released demo page remake with this feature. You can find more on [1.1.0 release - new demo page](https://github.com/KiraLT/torrent-stream-server/releases/tag/1.1.0)

![Screenshot from 2020-08-02 16-58-07](https://user-images.githubusercontent.com/10944908/89125772-785c3a00-d4e9-11ea-96ba-c49a60ab4b18.png)

**Comment by toonsevrin** [comment]
Wohooow, good job. I'll build it tomorrow!

**Comment by toonsevrin** [comment]
Just gave the new version a spin and what an awesome redesign, good job!!!
