### ISSUE TITLE
Download as zip

### ISSUE THREAD

**Issue by AyaanZaveri** [KiraLT/torrent-stream-server#202]
I would be great to have a button to download everything at once (via zip).

**Comment by KiraLT** [comment]
Added download zip feature. You can download all torrent files in a zip or download only selected file using zip. 

![Screenshot from 2021-09-14 19-17-38](https://user-images.githubusercontent.com/10944908/133295343-0650d2e4-dc19-4368-9b02-71d0180a7632.png)
