### ISSUE TITLE
Program reports itself as version 0.0.0

### ISSUE THREAD

**Issue by pataquets** [KiraLT/torrent-stream-server#24]
While tinkering with code, errors print `torrent-stream-server@0.0.0`, also.
```
$ node . serve --version
0.0.0
```

**Comment by KiraLT** [comment]
It only shows it when building from source. I wanted to set up a complete release workflow when deploying from Github UI, which:

1. Releases Docker container
2. Releases NPM package
3. Creates Git tag

But the issue was that I still needed to manually update package JSON from the source. So I removed the version from package.json.

NPM workflow changes version before releasing package ([npm-publish.yml](https://github.com/KiraLT/torrent-stream-server/blob/master/.github/workflows/npm-publish.yml#L42)). In the best-case scenario it should also update package.json, but I had trouble doing it with GitHub Actions.

In any case, we have a version in NPM packages, docker containers + git has version tag. Is there some need to also store version in the source?

**Comment by pataquets** [comment]
Actually, not that much. I found it when wanting to check version of the Docker image I was running for a container laughed with the `:latest` image tag.
Just reporting it, just in case.

**Comment by omgbox** [comment]
currently unable to build following /docs/setup#from-source , just to let you know. 

> git clone https://github.com/KiraLT/torrent-stream-server.git
> npm install
> npm run build
> npm run start

npm version 6.14.8
node version v12.19.0

- [ ] 1 verbose cli [
- [ ] 1 verbose cli   '/root/.nvm/versions/node/v12.19.0/bin/node',
- [ ] 1 verbose cli   '/root/.nvm/versions/node/v12.19.0/bin/npm',
- [ ] 1 verbose cli   'run',
- [ ] 1 verbose cli   'build'
- [ ] 1 verbose cli ]
- [ ] 2 info using npm@6.14.8
- [ ] 3 info using node@v12.19.0
- [ ] 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
- [ ] 5 info lifecycle torrent-stream-server@0.0.0~prebuild: torrent-stream-server@0.0.0
- [ ] 6 info lifecycle torrent-stream-server@0.0.0~build: torrent-stream-server@0.0.0
- [ ] 7 verbose lifecycle torrent-stream-server@0.0.0~build: unsafe-perm in lifecycle true
- [ ] 8 verbose lifecycle torrent-stream-server@0.0.0~build: PATH: /root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/torrent-stream-server/node_modu>9 verbose lifecycle torrent-stream-server@0.0.0~build: CWD: /root/torrent-stream-server
- [ ] 10 silly lifecycle torrent-stream-server@0.0.0~build: Args: [ '-c', 'npm run build-backend && npm run build-frontend' ]
- [ ] 11 silly lifecycle torrent-stream-server@0.0.0~build: Returned: code: 1  signal: null
- [ ] 12 info lifecycle torrent-stream-server@0.0.0~build: Failed to exec build script
- [ ] 13 verbose stack Error: torrent-stream-server@0.0.0 build: `npm run build-backend && npm run build-frontend`
- [ ] 13 verbose stack Exit status 1
- [ ] 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
- [ ] 13 verbose stack     at EventEmitter.emit (events.js:314:20)
- [ ] 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
- [ ] 13 verbose stack     at ChildProcess.emit (events.js:314:20)
- [ ] 13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
- [ ] 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
- [ ] 14 verbose pkgid torrent-stream-server@0.0.0
- [ ] 15 verbose cwd /root/torrent-stream-server
- [ ] 16 verbose Linux 4.4.0-19041-Microsoft
- [ ] 17 verbose argv "/root/.nvm/versions/node/v12.19.0/bin/node" "/root/.nvm/versions/node/v12.19.0/bin/npm" "run" "build"
- [ ] 18 verbose node v12.19.0
- [ ] 19 verbose npm  v6.14.8
- [ ] 20 error code ELIFECYCLE
- [ ] 21 error errno 1
- [ ] 22 error torrent-stream-server@0.0.0 build: `npm run build-backend && npm run build-frontend`
- [ ] 22 error Exit status 1
- [ ] 23 error Failed at the torrent-stream-server@0.0.0 build script.
- [ ] 23 error This is probably not a problem with npm. There is likely additional logging output above.
- [ ] 24 verbose exit [ 1, true ]

**Comment by KiraLT** [comment]
@pataquets version is back, I didn't have much success with automation, I will need to update the version old fashion way.

@omgbox could you provide more info about your setup (OS, virtualization)? Docker builds the source successfully after each commit.

**Comment by omgbox** [comment]
> @pataquets version is back, I didn't have much success with automation, I will need to update the version old fashion way.
> 
> @omgbox could you provide more info about your setup (OS, virtualization)? Docker builds the source successfully after each commit.

tested again, seems to build now, i am using the following. 
 
windows  10 64-bit with Linux subsystem WSL1 - Ubuntu 20.04 64-bit
node v12.19.1   (Latest LTS: Erbium)
npm 6.14.8

it is working perfectly. 

node . serve --version
1.5.2

**Comment by KiraLT** [comment]
I close this issue, the version is available in the master branch and will be released in the next release.

**Comment by pataquets** [comment]
@KiraLT Tested by pulling  `:latest` image tag, reports 1.5.2.
Image tag `:1.5.2` still reports 0.0.0, as expected, since it's previous to fixing. Anyway, with version tags it would be less problematic. The main problem was not being able to check with default, latest tag.
Unfortunately I can't help on automating the version string for NodeJS apps.
Thank you, @KiraLT .
