### ISSUE TITLE
possible streaming api issue using windows terminal  ?

### ISSUE THREAD

**Issue by omgbox** [KiraLT/torrent-stream-server#35]
i wasn't able to stream from terminal using the long magnet link within windows cmd

this will not work in cmd
mpv http://127.0.0.1:3000/stream/magnet link

 but this will perfectly work. 
mpv http://127.0.0.1:3000/stream?torrent=magnet link

**Comment by KiraLT** [comment]
The issue with the first link is that you probably wrongly escaped the magnet link. In the first link magnet can't have `?` symbol.

Ideally, you shouldn't generate links manually - use UI and copy links from UI.

**Comment by omgbox** [comment]
> The issue with the first link is that you probably wrongly escaped the magnet link. In the first link magnet can't have `?` symbol.
> 
> Ideally, you shouldn't generate links manually - use UI and copy links from UI.

tested it again, it seems to be working the same. i'm currently only using it through the terminal. 

i tried it again, like this , this is working. 

> mpv "http://example.com/stream?torrent=magnet:?xt=urn:btih:E5A04AF69BE755F3578214D020B9D94FCF1B0C3F"
>  (+) Video --vid=1 (*) (h264 1280x720 29.970fps)
>  (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
> AO: [wasapi] 48000Hz stereo 2ch float
> VO: [gpu] 1280x720 yuv420p
> AV: 00:00:03 / 01:53:09 (0%) A-V:  0.000 Dropped: 5 Cache: 49s/19MB


and using it like this gets parse torrent error . 

> https://example.com/stream/magnet:?xt=urn:btih:DEFC39C97728D03DE03407DE8B1EB1B92D3D6DFB

> {"error":"Cannot parse torrent: Invalid torrent identifier, link: magnet:"}


and using only the hash, it works but using the magnet:?xt=urn:btih: gives off parse error. 

> >mpv "https://example.com/stream/DEFC39C97728D03DE03407DE8B1EB1B92D3D6DFB"
 (+) Video --vid=1 (*) (h264 1280x720 29.970fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
AV: 00:00:02 / 01:22:22 (0%) A-V:  0.000 Dropped: 2 Cache: 30s/11MB

it's not a big deal for i'm able to use the hash.

**Comment by KiraLT** [comment]
That is the issue when trying to manually construct a URL. Try something like https://www.freeformatter.com/url-parser-query-string-splitter.html:

![Screenshot from 2020-11-16 13-26-44](https://user-images.githubusercontent.com/10944908/99247270-6770d380-280f-11eb-8198-a7aa1f007b7a.png)

As you can see parsed URL has:

**Path:** /stream/magnet:

How the correct URL should look:

![Screenshot from 2020-11-16 13-29-52](https://user-images.githubusercontent.com/10944908/99247619-e0702b00-280f-11eb-9f0c-ea4f7335abf7.png)
