### ISSUE TITLE
Please show me the this App version in footer or header like v1.5.2

### ISSUE THREAD

**Issue by manikandan-kyyba** [KiraLT/torrent-stream-server#39]
Please show me the this App version in footer or header like v1.5.2.
This must be helpful.

**Comment by KiraLT** [comment]
Added version to the header, it's available in the master and will be released with the next release:

![Screenshot from 2020-11-19 09-38-28](https://user-images.githubusercontent.com/10944908/99635741-15b48d00-2a4b-11eb-8102-7ec60ecfe9e7.png)

**Comment by manikandan-kyyba** [comment]
@KiraLT Thank you so much.
