### ISSUE TITLE
Need Better UI for Responsive

### ISSUE THREAD

**Issue by manikandan-kyyba** [KiraLT/torrent-stream-server#41]
Please try to put some web template apart from Bootstrap basic UI.

Check this Open Source UI

https://ant.design/components/overview

**Comment by KiraLT** [comment]
Could you give more details regarding it? Where responsive UI should be improved & maybe a few examples of how it should look?

**Comment by manikandan-kyyba** [comment]
Sure @KiraLT ,

We need web look like Netflix, Amazon Prime.

Web Template Example:

https://iqonic.design/themes/streamitnew/frontend/html/index.html
https://themeforest.net/item/streamit-video-streaming-html-admin-template/28369705

**Comment by KiraLT** [comment]
We have too little content to have a similar design. Also, we don't have images, only the torrent name. At the moment, it's overkill to change design from the scratch. The desktop design looks okay, so I think we should leave it as it is (maybe a dark theme would be nice). As for mobile (responsive), we should improve it, because at the moment it's not very convenient.

**Comment by KiraLT** [comment]
Maybe I will change the desktop design too. I found a nice dark theme: https://demos.creative-tim.com/black-dashboard-react/, I will try to minimize it and apply to this project.

**Comment by KiraLT** [comment]
Improved UI with dark theme support and better responsive design, it will be released soon.

![Screenshot from 2020-12-01 00-48-19](https://user-images.githubusercontent.com/10944908/100675117-026cc000-336f-11eb-8666-db2b27bc7450.png)
![Screenshot from 2020-12-01 00-48-04](https://user-images.githubusercontent.com/10944908/100675119-039ded00-336f-11eb-9d71-e9f818879078.png)
![Screenshot from 2020-12-01 00-47-49](https://user-images.githubusercontent.com/10944908/100675122-039ded00-336f-11eb-9737-ee9b2317f3ce.png)
![Screenshot from 2020-12-01 00-47-40](https://user-images.githubusercontent.com/10944908/100675124-04368380-336f-11eb-8c21-2518fd800c34.png)
