### ISSUE TITLE
heroku deploy not working

### ISSUE THREAD

**Issue by omgbox** [KiraLT/torrent-stream-server#6]
hi , i am trying to deploy to heroku, but it seems to show Application error, port is set on 80, if you can check what the problem is, because i have no idea :(

**Comment by omgbox** [comment]
looks like this is the error, 

npm ERR! Failed at the torrents-stream-server@1.1.1 start script.

maybe a compatible startup script would fix it.

**Comment by KiraLT** [comment]
Hello,

According to heroku (the same thing is with Google App Engine), the app should start the port specified by the PORT environment variable (`process.env.PORT`).

I added PORT env variable support with [the last commit](https://github.com/KiraLT/torrent-stream-server/commit/33ab889cf531fb14c637653ddfa539c765a44f30) - it should fix it. Please make sure that you don't overwrite the port in `config.json` file.

I also added the default NodeJs version in package JSON (check [this](https://github.com/KiraLT/torrent-stream-server/commit/61d7bf5d1042c3b4323bfbccdde39f58e0a49734)).

Finally, I tested by deploying to Heroku. I created a new Heroku project with the name `torrent-stream-server` and executed the following in this git repo:

1. `heroku login`
2. `heroku git:clone -a torrent-stream-server`
3. `git push heroku master`

And it successfully deployed to Heroku. If you have any more issues, please describe your deployment procedure.

P. S. I didn't use any `Procfile` and my `config.json` was empty

**Comment by omgbox** [comment]
I'm probably doing something wrong, was not able to test it

the steps i taken, created project called torrent-stream-server

next i did 

git clone https://github.com/KiraLT/torrent-stream-server.git

cd torrent-stream-server , next i did ~/torrent-stream-server$ heroku git:clone -a torrent-stream-server

returned result, 

fatal: destination path 'torrent-stream-server' already exists and is not an empty directory.

when i ls directory i can see all the files are there. not sure what the problem is.  i also tried to deploy from heroku's Deployment method github method. it builds, but i do not see anything on the page.

**Comment by KiraLT** [comment]
Regarding the first error, you are using the wrong command. You execute `git:clone`, but you need `git:remote` if you are already in a git repo! If you wish to use a clone, which clones repository from heroku, you will need to execute it in a clean directory, copy & commit files, and only then push (deploy).

I tested the following setup with a clean project named `torrent-stream-server7`:

- `git clone https://github.com/KiraLT/torrent-stream-server.git` (this should be your fork URL)
- `cd torrent-stream-server/`
- `heroku login`
- `heroku git:remote -a torrent-stream-server7`
- `git push heroku master`

But it only works for you if you have to write access to this repo. So **this only work in you is in your fork**. 

If you wish to deploy without a fork, you can clone git, reset, and add only heroku remote:

- `git clone https://github.com/KiraLT/torrent-stream-server.git`
- `cd torrent-stream-server/`
- `heroku login`
- `rm -rf .git` - remove all git files
- `git init` -  init clean git repo
- `heroku git:remote -a torrent-stream-server7`
- `git push heroku master`

**Make sure you are working with a clean heroku project - delete the old one or create a new one.**

Also, about GitHub deployment, if you are deploying your fork, make sure you have [this commit](https://github.com/KiraLT/torrent-stream-server/commit/33ab889cf531fb14c637653ddfa539c765a44f30). I see that you used `80` port, but Heroku may require a different port. Heroku passes the `PORT` environment variable, so you need to set the port according to this env variable.

**Comment by pataquets** [comment]
For the record, I've been able to *deploy* on Heroku without problems. Even I've not needed to write any Procfile.
However, as a warning everything I've added a magnet, everything looked to work OK, but soon thereafter I've received an automated mail from Heroku stating that my app has been suspended. I've even used a legit torrent magnet, but happens anyway.
I guess the cause to be either:
* Some overzealous outgoing firewall, since it's not unlikely that they have set limitations in place to avoid misusing their resources for piracy.
* The execution time for the process(es) exceeded som limit I'm unaware of.
Maybe it's some other limit or behaviour I still don't know but, since I've ruled out Heroku for hosting it anyway, I've not gone deeper.

**Comment by KiraLT** [comment]
Well, it may be because of legal reasons. I found that Heroku scans code dependencies and we have a lot of "interesting" dependencies. I will reopen this issue cause Heroku deployment can be very helpful - I will need to investigate why Heroku block this app and how can we solve it.

**Comment by pataquets** [comment]
Yes, my first bet was something related to piracy.
Furthermore, all the `npm audit`s that I've been indirectly run lately do complain about insecure libs. Maybe Heroku also has a policy about that. Not my best bet, but let's keep this in mind, anyway.

Also, once #10 is sorted out, we can deploy on Heroku using the Docker buildpack.

**Comment by omgbox** [comment]
> Well, it may be because of legal reasons. I found that Heroku scans code dependencies and we have a lot of "interesting" dependencies. I will reopen this issue cause Heroku deployment can be very helpful - I will need to investigate why Heroku block this app and how can we solve it.

tried to deploy again with clean, install same issue, the app gets automatically suspended after build. you should probably check live-torrent-server project on github and see how this guy got the modules installed. located [here,](https://live-torrent-server.herokuapp.com/docs/api/torrent.html#selectors)  , i have this project running and working really good, with a cdn77 and bunnycdn, you could stream torrents within few seconds, range requests also work.

**Comment by pataquets** [comment]
Browsing the dependency graph, I've found a security issue in one of the dependencies of torrent-stream. See mafintosh/torrent-stream#191, for which there is an open PR, albeit stale.
Torrent-stream needs some serious dependency upgrading.

I guess there might be more packages with security issues.

**Comment by omgbox** [comment]
> torrent-stream

Dependency Status out of date 

9 modules are out of date

https://david-dm.org/mafintosh/torrent-stream#info=devDependencies

something else to share, ffmpeg in wasm . encode videos in your browser. interesting since many people are using h265, our browsers do not support decoder native . so using this would be interesting. 

https://ffmpegwasm.github.io/

**Comment by KiraLT** [comment]
@pataquets @omgbox  [torrent-stream](https://github.com/mafintosh/torrent-stream) has a lot of deprecated dependencies + it hasn't been updated for a long time.  With my [recent commit](https://github.com/KiraLT/torrent-stream-server/commit/1a4a326d0fece49279a4c9bf82f6737d87a7666a) I replaced it with [webtorrent](https://github.com/webtorrent/webtorrent)- it has a larger community and better performance. I will need to do further testing to make sure that everything works perfectly.

@omgbox it looks nice, we should try including it.

**Comment by KiraLT** [comment]
I tried deploying to Heroku again and it deployed successfully & it was not suspended. All previous deployments were instant suspended, so it's something new.

I deployed using:
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/KiraLT/torrent-stream-server)

Let's see how long it will last.

**Comment by omgbox** [comment]
> I tried deploying to Heroku again and it deployed successfully & it was not suspended. All previous deployments were instant suspended, so it's something new.
> 
> I deployed using:
> [![Deploy](https://camo.githubusercontent.com/6979881d5a96b7b18a057083bb8aeb87ba35fc279452e29034c1e1c49ade0636/68747470733a2f2f7777772e6865726f6b7563646e2e636f6d2f6465706c6f792f627574746f6e2e737667)](https://heroku.com/deploy?template=https://github.com/KiraLT/torrent-stream-server)
> 
> Let's see how long it will last.


great news, its working perfectly , nyaa working 👍 

how would I stream from outside of the interface for example, on my terminal  this only works if i use the full url with the filename. 

this work
`mpv "https://example.herokuapp.com/stream?torrent=841BC22850387BB471D948472A971C85B6D3157A&file=%EB%A7%9B%EC%9E%88%EB%8A%94%20%EB%85%80%EC%84%9D%EB%93%A4.E298.201106.720p-NEXT.mp4" `

but this is not working.
mpv  "https://example.herokuapp.com/stream?torrent=841BC22850387BB471D948472A971C85B6D3157A/"

does the api filter selector which method to automatically select video without appending the full file name. 

something like this would be cool 

mpv  "https://example.herokuapp.com/stream?torrent=841BC22850387BB471D948472A971C85B6D3157A/:video"

/:video will select the largest video file in torrent. 
/:1,2,3,4,5 number selectors could be the index numbers on the torrent. to pick from.

**Comment by KiraLT** [comment]
@omgbox at the moment it is possible to select only by filename. Could you create a new issue and describe which selectors should be useful?

**Comment by KiraLT** [comment]
Heroku seems working fine for several days, so I can close this issue. The only thing I noticed that it sometimes crash because of high download speed (one time it reached 40MB/s), but we have a separate issue for that: #15.

**Comment by pataquets** [comment]
Watch out #32
