### ISSUE TITLE
Handle TERM signal

### ISSUE THREAD

**Issue by pataquets** [KiraLT/torrent-stream-server#61]
Whenever the system, user or whatever external agent wants to stop a process, the `SIGTERM` signal is used. `SIGTERM` is meant to be a clean shutdown signal, which the app can catch (trap) and do its shutdown cleanly.

In Docker, this is done issuing a `docker stop` command to the container, which will cause the Docker daemon sending the `SIGTERM` signal to the container's pid 1 process. After a configurable timeout, Docker will send a `SIGKILL` signal if the container has not stopped.

Since previously TSS was started using a `CMD` statement, that implied a `sh -c` `ENTRYPOINT`. The `sh` process got the `TERM` signal and exited, forcefully killing its children.
As of now, `node` binary runs as pid 1, so it proxy the `TERM` signal to the running app, which can process it to shutdown cleanly. On most programming languages, you have to explicitly set a handler function to process it (trap the signal). Currently, TSS does not process it and Docker kills it after timeout (by default 10s).

More info: https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/

**Comment by KiraLT** [comment]
Added graceful shutdown support on `SIGTERM` or `SIGINT` signals. It will close all open HTTP connections + shutdown torrent client.

**Comment by pataquets** [comment]
Tested. Now `docker stop` shuts down TSS container gracefully (exit code 0).
Thank you, @KiraLT!
