### ISSUE TITLE
Can't pull Docker image anonymously

### ISSUE THREAD

**Issue by pataquets** [KiraLT/torrent-stream-server#7]
I wanted to try & tinker with this software.

Since there is `Dockerfile` and Docker package, I went for it.

This is what happened:
```
$ docker run --rm -it ghcr.io/kiralt/torrent-stream-server:1.2.0
Unable to find image 'ghcr.io/kiralt/torrent-stream-server:1.2.0' locally
docker: Error response from daemon: Get https://ghcr.io/v2/kiralt/torrent-stream-server/manifests/1.2.0: denied.
```
I can pull from Docker Hub without problems.

**Comment by KiraLT** [comment]
I redeployed the latest version on ghcr.io, which supports anonymous access. You can find the package [here](https://github.com/users/KiraLT/packages/container/package/torrent-stream-server).

**Comment by pataquets** [comment]
Awesome! It worked. 
I have been able to try it out. I have feedback, filling separate issue.
Thanks.
