### ISSUE TITLE
Feature request: Append configurable fixed string to added magnet URIs (e.g. trackers)

### ISSUE THREAD

**Issue by pataquets** [KiraLT/torrent-stream-server#9]
Getting familiar with the code, I've seen that, although `parse-torrent` only gets the infoHash, `torrent-stream` still gets the full magnet URI and can take advantage of trackers embedded in the URI.

Since trackers come and go and some magnet URIs don't even have trackers built-in, adding some well-known (or even private) trackers would speed up stream bootstrap and discovery.

This could be accomplished at add time by just automatically appending a fixed string containing some bootstraping, well-known trackers encoded in a URI parameter string.

As you can't anticipate which URIs will need it and which trackers each user would find best, it would be a nice addition﻿ to let the user configure their own string, although it can default to some popular public trackers as example (commented out, for instance).

Notice I'm requesting a fixed *generic* string, which will initially be of use for adding trackers, but it might be used for other purposes, as long as it is kept generic enough. If `torrent-stream` lib were to support it, it could also be used to bootstrap the torrent from a well-known peer by adding a `x.pe` URI parameter, for instance (see BEP 9).

**Comment by KiraLT** [comment]
Could you give more details on how it should look from the user experience?

1. Should it be a separate page, where you select torrent (agent or file) and then you can edit torrent meta & then generate a new agent link?
1. Should we just add an option to append extra torrent arguments on home page?
1. Or maybe it is possible to add it to the config & append to all torrents automatically? 

Let me know your thoughts

**Comment by pataquets** [comment]
Good point. For my use case, I was thinking of a `config.json` setting, with no configuration UI or knobs visible to the user anywhere in the UI. Just always adding the string silently.
No user intervention, neither for adding or preventing it.

I can't think of any case which could be useful to have it exposed in the UI, but meybe it's just me being biased on my own use case.

**Comment by KiraLT** [comment]
I added auto default trackers (they are automatically downloaded from [ngosang/trackerslist](https://github.com/ngosang/trackerslist)).

I also added the ability to configure `tr`, `ws`,  `x.pe` parameters. I see webtorrent supports `x.pe` according to [Support 'x.pe' parameter on magnet URIs](https://github.com/webtorrent/webtorrent/issues/1939)

```ts
export interface Config {
    ...
    torrents: {
        ...
        /**
         * Load defaul trackers list & use it for each torrents
         */
        useDefaultTrackers: boolean
        /**
         * Additional trackers (`tr` parameter) which will be appened to each torrent
         */
        announce: string[]
        /**
         * Web Seed (`ws` parameter) which will be appened to each torrent
         */
        urlList: string[]
        /**
         * Peer addresses (`x.pe` parameter)
         */
        peerAddresses: string[]
    }
    ...
}
```
